[tool.ruff]
line-length = 150
exclude = ["tests/*", "data/*"]

[tool.ruff.lint]
select = ["E", "F", "W", "C90", "I", "B"]

[tool.ruff.lint.isort]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
known-third-party = ["pyspark", "requests", "pytest", "dotenv"]
known-first-party = ["src"]
