[tool.ruff]
line-length = 150
exclude = ["tests/*", "data/*"]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings  
    "F",   # pyflakes
    "C90", # mccabe complexity
    "I",   # isort
    "N",   # pep8-naming
]

[tool.ruff.lint.isort]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
known-third-party = ["pyspark", "requests", "pytest", "dotenv"]
known-first-party = ["src"]

[tool.ruff.lint.mccabe]
max-complexity = 15
